// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADDLkLZyBFz5cM1jIwkBv5Ulza_7TQ2cw',
    appId: '1:183855244965:web:3ce83cc95c07d6e34fcf4c',
    messagingSenderId: '183855244965',
    projectId: 'mobileapp-67ab4',
    authDomain: 'mobileapp-67ab4.firebaseapp.com',
    storageBucket: 'mobileapp-67ab4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2QEa7J6S0XGai6LuCKx9OL_b8dDmXd-k',
    appId: '1:183855244965:android:285ebdf816add8864fcf4c',
    messagingSenderId: '183855244965',
    projectId: 'mobileapp-67ab4',
    storageBucket: 'mobileapp-67ab4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA240hSgTFouniLpf_eS7yppADOR8SqBgc',
    appId: '1:183855244965:ios:169cfdf9c3de49264fcf4c',
    messagingSenderId: '183855244965',
    projectId: 'mobileapp-67ab4',
    storageBucket: 'mobileapp-67ab4.appspot.com',
    iosClientId: '183855244965-j543011tkprpj2gblolp902n7a9l8icd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA240hSgTFouniLpf_eS7yppADOR8SqBgc',
    appId: '1:183855244965:ios:b96b702f48302d204fcf4c',
    messagingSenderId: '183855244965',
    projectId: 'mobileapp-67ab4',
    storageBucket: 'mobileapp-67ab4.appspot.com',
    iosClientId: '183855244965-no2ftstmatee7fb8inoe18go23e89n5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAplication.RunnerTests',
  );
}
